name: RPGLootTables
version: '${project.version}'
main: ca.rpgcraft.rpgloottables.RPGLootTables
api-version: 1.18
authors: [ dsevvv ]
description: Plugin that controls the loot tables for naturally generated chests.
website: github.com/dsevvv/rpgloottables
softdepend:
  - Vault
commands:
  rpgloot:

  rpgl:

  rloot:

  rl:
